// GENERATED by: cargo run -- dump-open-api > openapi.yaml
// Regenerate with: cargo run -- dump-open-api > src/api/openapi.yaml
pub const OPENAPI_YAML: &str = include_str!("openapi.yaml");

/// Serve the OpenAPI spec as YAML — static file, no serde_yaml needed.
pub async fn openapi_yaml() -> impl axum::response::IntoResponse {
    ([("content-type", "application/x-yaml")], OPENAPI_YAML)
}
